ENABLE_PROMPT_CONTEXT_LOGGING = False
ENABLE_PROMPT_LOGGING = False
ENABLE_METHOD_CALLED_LOGGING = False
ENABLE_OPENAI_RESPONSE_LOGGING = False
ENABLE_WORLD_EVENT_LOGGING = True
ENABLE_AGENT_EVENT_LOGGING = True
